### ISSUE TITLE
Add considerations section

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/parent-signals-dot#21]
We should probably add a section to the draft on why we chose this methodology rather than using TLSA records etc...

This could be based on some of the stuff we have/had in readme.md

**Comment by chantra** [comment]
I see value in providing this info while the discussion is ongoing, but then it is not clear to me if it would make sense in final document. It is kind of hard to draw the line where enough/too much text is. The comparisons of approaches is probably another document it itself. 

It may be easier in formulating this by explaining the goals of this approach: no change in auth/registries and avoiding probing from resolver? Which is to some extend what is already in the intro.

**Comment by Habbie** [comment]
> I see value in providing this info while the discussion is ongoing, but then it is not clear to me if it would make sense in final document.

We can mark it 'remove before publication', but I am also not sure we should do it at all.



> The comparisons of approaches is probably another document it itself.

There are one or two such documents already (I can look them up later) but they are more of an idea dump - like our README.md.

> It may be easier in formulating this by explaining the goals of this approach: no change in auth/registries and avoiding probing from resolver? Which is to some extend what is already in the intro.

Yes, describing the constraints we assumed would be good.

**Comment by Habbie** [comment]
> Yes, describing the constraints we assumed would be good.

And, because those are not exactly the same, the constraints we happen to match, such as 'no extra round trips'. It was not a design goal but we got it for free.

**Comment by RobinGeuze** [comment]
Closing this because #35 was added.
