### ISSUE TITLE
resolver behaviour section

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/parent-signals-dot#24]
Explaining the whole protocol from the resolver perspective would probably avoid a big chunk of the confusion we saw on the WG. https://mailarchive.ietf.org/arch/msg/dns-privacy/Vd15sMnExVb7EL6jJ_21SkyhB-c is a good start.

**Comment by chantra** [comment]
I suppose that text with some [TBD] to replace algo number and using example.{net,com} can be put directly in "Validating resolver changes" section. I am happy to do some initial text in a PR.

**Comment by Habbie** [comment]
I was unsure it should go in that section or in a separate section. Both really are just 'applied clarifications'. Your PR would be very welcome :)

**Comment by chantra** [comment]
will try to prioritize this shortly.

**Comment by chantra** [comment]
ok, added some text, or rather explained the workflow that a resolver would follow to authenticate the DoT server. Not sure it is clarifying much :D.
