### ISSUE TITLE
Is DoT good enough for an AD bit?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/parent-signals-dot#7]
First, we need to decide on this (and I trust that the WG will pick a fight over this).

Second, if the conclusion is 'yes', we need to write some words on what that means for validators that talk to an upstream resolver, because we cannot forward them DNSKEYs and RRSIGs that allow them to do their own validation.

**Comment by RobinGeuze** [comment]
My thoughts:
We should say something along the lines of "In theory this could partially replace DNSSEC in the future, however this document does not cover that, due to the complexity it adds in regards to the current abundance of validators that use an upstream resolver. If a future standard does decide to implement this a concern it should address is how a validator with an upstream resolver an still determine data authenticity."

**Comment by chantra** [comment]
So this is a tricky one. In some cases, it may be good enough but not for all cases.

Take an example where an organization generate their zone and host their DNS servers. DoT ensure that the content has not been changed in flight and given that this is the same organization creating the zone, pretty much you could validate the content. I think it would give you roughly the same level of authenticity as online signing.

Now, take a case where an organization owns their zone, dnssec signed it and has third-party secondaries serving the content. Even though you can authenticate the server, there is no guarantee that the third-party is not modifying the content you have given them.

**Comment by rgacogne** [comment]
> Now, take a case where an organization owns their zone, dnssec signed it and has third-party secondaries serving the content. Even though you can authenticate the server, there is no guarantee that the third-party is not modifying the content you have given them.

Agreed. It seems to me that, even with a public key protected by DNSSEC, DoT only protects the transport and that's not enough to authenticate the content, which is what the AD bit is about.

**Comment by RobinGeuze** [comment]
Lets close this, I do not think this draft should imply that DoT can be used to verify well enough to set the AD bit.
